{ inputs, self, ... }: {
  # Fonte única das ações do DMS; cada compositor adapta apenas a sintaxe.
  flake.lib.dmsBinds = { lib, session, executable ? "dms" }:
    let
      common = [
        { mods = "SUPER"; key = "d"; command = "ipc call spotlight toggle"; }
        { mods = "SUPER"; key = "Escape"; command = "ipc call powermenu toggle"; }
        { mods = "SUPER"; key = "F1"; command = "ipc call keybinds toggle ${session}"; }
        { key = "Print"; command = "screenshot"; }
        { key = "XF86AudioRaiseVolume"; command = "ipc call audio increment 3"; repeating = true; locked = true; }
        { key = "XF86AudioLowerVolume"; command = "ipc call audio decrement 3"; repeating = true; locked = true; }
        { key = "XF86AudioMute"; command = "ipc call audio mute"; locked = true; }
        { key = "XF86MonBrightnessUp"; command = "ipc call brightness increment 5"; repeating = true; locked = true; }
        { key = "XF86MonBrightnessDown"; command = "ipc call brightness decrement 5"; repeating = true; locked = true; }
      ];
      binds = common ++ lib.optionals (session == "hyprland") [
        { mods = "SUPER"; key = "Space"; command = "ipc call spotlight toggle"; }
        { mods = "SUPER+ALT"; key = "L"; command = "ipc call lock lock"; }
      ];
      luaString = builtins.toJSON;
    in {
      mango = map (b: "${b.mods or "NONE"},${b.key},spawn_shell,${executable} ${b.command}") binds;
      hyprland = lib.concatMapStringsSep "\n" (b:
        let
          keys = lib.optionalString (b ? mods) (lib.replaceStrings [ "+" ] [ " + " ] b.mods + " + ") + b.key;
          flag = value: if value then "true" else "false";
        in "hl.bind(${luaString keys}, hl.dsp.exec_cmd(${luaString "${executable} ${b.command}"}), { repeating = ${flag (b.repeating or false)}, locked = ${flag (b.locked or false)} })"
      ) binds;
    };

  flake.nixosModules.dms = { lib, username, ... }: {
    imports = [ inputs.dms.nixosModules.default ];

    programs.dank-material-shell.enable = true;

    # DMS é usado apenas na sessão Mango.
    home-manager.users.${username}.wayland.windowManager = {
      # O DMS é a
      # própria shell da sessão lá (`exec-once=dms run`), e as cores/layout/
      # window rule abaixo eram os dms/colors.conf, dms/layout.conf e
      # dms/windowrules.conf do zip original — todos marcados como
      # "auto-generated by DMS" (regenerados por `dms setup`, não à mão).
      mango.settings = {
        # Chamadas ao `dms` via bind precisam de `spawn_shell` (não `spawn`),
        # senão o mango não expande os argumentos do IPC corretamente. Ficam
        # sempre ativos (sem o `lib.mkIf` do Hyprland acima) porque o DMS é a
        # shell da sessão no MangoWM.
        bind = (self.lib.dmsBinds { inherit lib; session = "mangowm"; }).mango;

        # dms/colors.conf original
        bordercolor = "0x948f99ff";
        focuscolor = "0xd0bcffff";
        urgentcolor = "0xf2b8b5ff";

        # dms/layout.conf original
        border_radius = 12;
        borderpx = 2;
        gappih = 4;
        gappiv = 4;
        gappoh = 4;
        gappov = 4;

        # dms/windowrules.conf original
        windowrule = [
          "appid:^com.danklinux.dms$,isfloating:1"
        ];

        # system.conf original — inicia a shell do DMS no arranque do mango.
        "exec-once" = [ "dms run" ];
      };
    };
  };
}
