{ inputs, ... }: {
  flake.nixosModules.dms = { username, ... }: {
    imports = [ inputs.dms.nixosModules.default ];

    programs.dank-material-shell.enable = true;

    # DMS é usado apenas na sessão Mango.
    home-manager.users.${username}.wayland.windowManager = {
      # O DMS é a
      # própria shell da sessão lá (`exec-once=dms run`), e as cores/layout/
      # window rule abaixo eram os dms/colors.conf, dms/layout.conf e
      # dms/windowrules.conf do zip original — todos marcados como
      # "auto-generated by DMS" (regenerados por `dms setup`, não à mão).
      mango.settings = {
        # Chamadas ao `dms` via bind precisam de `spawn_shell` (não `spawn`),
        # senão o mango não expande os argumentos do IPC corretamente. Ficam
        # sempre ativos (sem o `lib.mkIf` do Hyprland acima) porque o DMS é a
        # shell da sessão no MangoWM.
        bind = [
          "SUPER,d,spawn_shell,dms ipc call spotlight toggle"
          "SUPER,Escape,spawn_shell,dms ipc call powermenu toggle"
          "SUPER,F1,spawn_shell,dms ipc call keybinds toggle mangowm"
          "NONE,Print,spawn_shell,dms screenshot"
          "NONE,XF86AudioRaiseVolume,spawn_shell,dms ipc call audio increment 3"
          "NONE,XF86AudioLowerVolume,spawn_shell,dms ipc call audio decrement 3"
          "NONE,XF86AudioMute,spawn_shell,dms ipc call audio mute"
          "NONE,XF86MonBrightnessUp,spawn_shell,dms ipc call brightness increment 5"
          "NONE,XF86MonBrightnessDown,spawn_shell,dms ipc call brightness decrement 5"
        ];

        # dms/colors.conf original
        bordercolor = "0x948f99ff";
        focuscolor = "0xd0bcffff";
        urgentcolor = "0xf2b8b5ff";

        # dms/layout.conf original
        border_radius = 12;
        borderpx = 2;
        gappih = 4;
        gappiv = 4;
        gappoh = 4;
        gappov = 4;

        # dms/windowrules.conf original
        windowrule = [
          "appid:^com.danklinux.dms$,isfloating:1"
        ];

        # system.conf original — inicia a shell do DMS no arranque do mango.
        "exec-once" = [ "dms run" ];
      };
    };
  };
}
